# Generated by Django 3.2 on 2021-12-23 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('SEMILLAS', 'Semillas'), ('ARRENDAMIENTO', 'Arrendamiento'), ('FUMIGACION', 'Fumigación'), ('LABORES_VARIAS', 'Labores Varias'), ('FERTILIZACION', 'Fertilización'), ('AGROQUIMICOS', 'Agroquimicos'), ('COSECHA', 'Cosecha'), ('SIEMBRA', 'Siembra'), ('DIF_DE_CAMBIO', 'Dif. de cambio'), ('AJUSTE', 'Ajuste'), ('VARIOS', 'Varios'), ('COMBUSTIBLE', 'Combustible')], default='VARIOS', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Articulos',
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_vto', models.DateField()),
                ('numero', models.CharField(max_length=255)),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=30, null=True)),
                ('impuesto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
                ('otro_importe', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
                ('rubro', models.CharField(choices=[('VARIOS', 'Varios'), ('AGROQUIMICOS', 'Agroquimicos'), ('FERTILIZANTES', 'Fertilizantes'), ('SEMILLAS', 'Semillas'), ('LABORES', 'Labores'), ('DIF_DE_CAMBIO', 'Dif. de cambio'), ('INTERESES', 'Intereses'), ('HONORARIOS', 'Honorarios'), ('SERVICIOS', 'Servicios'), ('COMBUSTIBLE', 'Combustible'), ('ARRENDAMIENTOS', 'Arrendamientos')], default='VARIOS', max_length=255)),
                ('estado_pago', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='InstrumentoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('instrumento', models.CharField(choices=[('CHEQUE', 'Cheque'), ('E-CHEQ', 'E-cheq'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO', 'Efectivo')], default='CHEQUE', max_length=255)),
                ('numero_instrumento', models.CharField(blank=True, max_length=255)),
                ('fecha_instrumento', models.DateField(blank=True, null=True)),
                ('institucion_instrumento', models.CharField(choices=[('MACRO', 'Macro'), ('GALICIA', 'Galicia'), ('CAJA', 'Caja')], default='MACRO', max_length=255)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_uilizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('cuit', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='NotaDeCredito',
            fields=[
                ('factura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comprobantes.factura')),
            ],
            bases=('comprobantes.factura',),
        ),
        migrations.CreateModel(
            name='NotaDeDebito',
            fields=[
                ('factura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comprobantes.factura')),
            ],
            bases=('comprobantes.factura',),
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facturas', models.ManyToManyField(related_name='pagos', to='comprobantes.Factura')),
                ('instrumentos', models.ManyToManyField(related_name='pagos', to='comprobantes.InstrumentoPago')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprobantes.proveedor')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='ItemFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comprobantes.articulo')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comprobantes.factura')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.AddField(
            model_name='instrumentopago',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comprobantes.proveedor'),
        ),
        migrations.AddField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprobantes.proveedor'),
        ),
    ]
