# Generated by Django 3.2 on 2022-03-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0003_empresarepresentada'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cosecha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
