# Generated by Django 3.2 on 2022-04-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0005_pagos_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notadecredito',
            options={'verbose_name': 'Nota de Crédito', 'verbose_name_plural': 'Notas de Crédito'},
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tipo',
            field=models.CharField(choices=[('FLETES', 'FLETES'), ('ART24COVEI', 'ART24COVEI'), ('INTERESES', 'INTERESES'), ('SEMILLAS', 'Semillas'), ('ARRENDAMIENTO', 'Arrendamiento'), ('FUMIGACION', 'Fumigación'), ('LABORES_VARIAS', 'Labores Varias'), ('FERTILIZACION', 'Fertilización'), ('AGROQUIMICOS', 'Agroquimicos'), ('COSECHA', 'Cosecha'), ('SIEMBRA', 'Siembra'), ('DIF_DE_CAMBIO', 'Dif. de cambio'), ('AJUSTE', 'Ajuste'), ('VARIOS', 'Varios'), ('COMBUSTIBLE', 'Combustible')], default='VARIOS', max_length=255),
        ),
        migrations.AlterField(
            model_name='factura',
            name='rubro',
            field=models.CharField(choices=[('VARIOS', 'Varios'), ('FLETES', 'Fletes'), ('AGROQUIMICOS', 'Agroquimicos'), ('FERTILIZANTES', 'Fertilizantes'), ('SEMILLAS', 'Semillas'), ('LABORES', 'Labores'), ('DIF_DE_CAMBIO', 'Dif. de cambio'), ('INTERESES', 'Intereses'), ('HONORARIOS', 'Honorarios'), ('SERVICIOS', 'Servicios'), ('COMBUSTIBLE', 'Combustible'), ('ARRENDAMIENTOS', 'Arrendamientos')], default='VARIOS', max_length=255),
        ),
    ]
