# Generated by Django 3.2 on 2022-04-13 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0006_auto_20220406_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfactura',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='comprobantes.factura'),
        ),
    ]
