# Generated by Django 3.2 on 2022-04-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0007_alter_itemfactura_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfactura',
            name='articulo',
            field=models.ForeignKey(blank=True, default='VARIOS', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='comprobantes.articulo'),
        ),
    ]
