# Generated by Django 3.2 on 2022-04-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0008_alter_itemfactura_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='ventas',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
