# Generated by Django 3.2 on 2022-05-16 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comprobantes', '0012_empresarepresentada_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresarepresentada',
            name='usuario',
        ),
        migrations.AddField(
            model_name='empresarepresentada',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
