# Generated by Django 3.2 on 2022-05-17 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comprobantes', '0014_auto_20220517_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresarepresentada',
            name='usuario',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
