# Generated by Django 3.2 on 2022-07-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0016_alter_factura_cosecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notadedebito',
            options={'verbose_name': 'Nota de Débito', 'verbose_name_plural': 'Notas de Débito'},
        ),
    ]
