# Generated by Django 3.2 on 2022-01-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartadeporte',
            name='cosecha',
            field=models.CharField(choices=[('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025')], default='2021/2022', max_length=255),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='direccion_procedencia',
            field=models.CharField(blank=True, choices=[('Zona Rural S/N', 'z/rural')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='grano',
            field=models.CharField(choices=[('SOJA', 'soja'), ('MAIZ', 'maíz'), ('TRIGO', 'trigo'), ('GIRASOL', 'girasol'), ('SORGO', 'sorgo')], default='SOJA', max_length=255),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='localidad_procedencia',
            field=models.CharField(blank=True, choices=[('Maria Teresa', 'M. Teresa'), ('San Gregorio', 'Sn. Gregorio'), ('Teodelina', 'Teodelina')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='provincia_procedencia',
            field=models.CharField(blank=True, choices=[('Santa fe', 'Santa Fe'), ('Cordoba', 'Córdoba')], max_length=255, null=True),
        ),
    ]
