# Generated by Django 3.2 on 2022-02-17 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0002_auto_20220124_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hectareas', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=255)),
                ('provincia', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlanSiembra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie_sembrada', models.IntegerField()),
                ('cultivo', models.CharField(choices=[('SOJA', 'soja'), ('MAIZ', 'maíz'), ('TRIGO', 'trigo'), ('GIRASOL', 'girasol'), ('SORGO', 'sorgo')], default='SOJA', max_length=20)),
                ('variedad', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=600)),
                ('campania', models.CharField(choices=[('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025')], max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercaderias.campo')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
