# Generated by Django 3.2 on 2022-02-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0003_campo_plansiembra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='hectareas',
            field=models.FloatField(),
        ),
    ]
