# Generated by Django 3.2 on 2022-03-23 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0005_auto_20220317_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesificacionContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('kilos_pesificados', models.BigIntegerField()),
                ('tipo_de_cambio', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercaderias.contratomercaderia')),
            ],
        ),
        migrations.CreateModel(
            name='FijacionContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('kilos_fijados', models.BigIntegerField()),
                ('precio', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercaderias.contratomercaderia')),
            ],
        ),
    ]
