# Generated by Django 3.2 on 2022-04-06 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0006_auto_20220406_1612'),
        ('mercaderias', '0006_fijacioncontrato_pesificacioncontrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cultivo', models.CharField(choices=[('SOJA', 'soja'), ('MAIZ', 'maíz'), ('TRIGO', 'trigo'), ('GIRASOL', 'girasol'), ('SORGO', 'sorgo')], default='SOJA', max_length=20)),
                ('campania', models.CharField(choices=[('2015/2016', '2015/2016'), ('2016/2017', '2016/2017'), ('2017/2018', '2017/2018'), ('2018/2019', '2018/2019'), ('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025')], max_length=60)),
                ('labor', models.CharField(max_length=60)),
                ('tipo_labor', models.CharField(max_length=60)),
                ('dosis', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mercaderias.campo')),
                ('contratista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comprobantes.proveedor')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comprobantes.articulo')),
                ('titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comprobantes.empresarepresentada')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
