# Generated by Django 3.2 on 2022-04-06 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0006_auto_20220406_1612'),
        ('mercaderias', '0007_ordendelabor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendelabor',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comprobantes.itemfactura'),
        ),
    ]
