# Generated by Django 3.2 on 2022-04-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0006_auto_20220406_1612'),
        ('mercaderias', '0009_remove_ordendelabor_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendelabor',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='ordendelabor',
            name='insumo',
        ),
        migrations.CreateModel(
            name='ItemLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comprobantes.articulo')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mercaderias.ordendelabor')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
