# Generated by Django 3.2 on 2022-04-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0010_auto_20220407_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendelabor',
            name='campo',
        ),
        migrations.AddField(
            model_name='ordendelabor',
            name='campo',
            field=models.ManyToManyField(blank=True, null=True, to='mercaderias.Campo'),
        ),
    ]
