# Generated by Django 3.2 on 2022-04-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0011_auto_20220407_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendelabor',
            name='campo',
            field=models.ManyToManyField(blank=True, to='mercaderias.Campo'),
        ),
    ]
