# Generated by Django 3.2 on 2022-04-13 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0012_alter_ordendelabor_campo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartadeporte',
            name='direccion_procedencia',
            field=models.CharField(blank=True, choices=[('Zona Rural S/N', 'z/rural'), ('Silioni', 'Silioni'), ('San Enrique', 'San Enrique'), ('Vidaurre', 'Vidaurre'), ('Benjamin Rodriguez', 'Benjamin Rodriguez'), ('Del Sol', 'Del Sol')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='localidad_procedencia',
            field=models.CharField(blank=True, choices=[('Corral de Bustos', 'Corral de Bustos'), ('Maria Teresa', 'M. Teresa'), ('San Gregorio', 'Sn. Gregorio'), ('Teodelina', 'Teodelina')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemlabor',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='mercaderias.ordendelabor'),
        ),
    ]
