# Generated by Django 3.2 on 2022-04-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0013_auto_20220413_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartadeporte',
            name='destinatario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='mercaderias.destinatario'),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='destino',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='mercaderias.destino'),
        ),
    ]
