# Generated by Django 3.2 on 2022-04-22 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0015_alter_cartadeportedescargada_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartadeporte',
            name='establecimiento',
            field=models.CharField(choices=[('Silioni', 'Silioni'), ('San Enrique', 'San Enrique'), ('Vidaurre', 'Vidaurre'), ('Benjamin Rodriguez', 'Benjamin Rodriguez'), ('Del Sol', 'Del Sol')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cartadeporte',
            name='direccion_procedencia',
            field=models.CharField(default='ZONA RURAL', max_length=255),
        ),
        migrations.AlterField(
            model_name='cartadeportedescargada',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mercaderias.contratomercaderia'),
        ),
    ]
