# Generated by Django 3.2 on 2022-06-02 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0016_alter_factura_cosecha'),
        ('mercaderias', '0018_plansiembra_titular'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comprobantes.empresarepresentada'),
        ),
    ]
