# Generated by Django 3.2 on 2022-06-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0020_arrendamiento_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrendamiento',
            name='toneladas_x_ha',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
